//
//  Copyright © 2026 Hidden Spectrum, LLC.
//

@testable import SwiftStringCatalog

import Testing

@Suite("_CatalogEntry")
struct _CatalogEntryTests {

    @Test("init(from:) preserves metadata and standalone localizations")
    func initFromStringGroupPreservesMetadata() throws {
        let stringGroup = LocalizableStringGroup(
            comment: "Greeting",
            isCommentAutoGenerated: true,
            extractionState: .manual,
            generatesSymbol: true,
            shouldTranslate: false,
            strings: [
                LocalizableString(kind: .standalone, sourceKey: "Hello", targetLanguage: .english, translatedValue: "Hello", state: .translated),
                LocalizableString(kind: .standalone, sourceKey: "Hello", targetLanguage: .french, translatedValue: "Bonjour", state: .needsReview)
            ]
        )
        
        let entry = try _CatalogEntry(from: stringGroup)
        
        #expect(entry.comment == "Greeting")
        #expect(entry.isCommentAutoGenerated == true)
        #expect(entry.extractionState == .manual)
        #expect(entry.generatesSymbol == true)
        #expect(entry.shouldTranslate == false)
        #expect(entry.localizations?[.english]?.stringUnit?.value == "Hello")
        #expect(entry.localizations?[.french]?.stringUnit?.state == .needsReview)
    }
    
    @Test("init(from:) builds nested string set and substitution structures")
    func initFromStringGroupBuildsNestedStructures() throws {
        let stringGroup = LocalizableStringGroup(
            comment: nil,
            isCommentAutoGenerated: nil,
            extractionState: .manual,
            generatesSymbol: nil,
            shouldTranslate: nil,
            strings: [
                LocalizableString(kind: .stringSet(index: 0), sourceKey: "One", targetLanguage: .english, translatedValue: "One", state: .translated),
                LocalizableString(kind: .stringSet(index: 2), sourceKey: "Three", targetLanguage: .english, translatedValue: "Three", state: .needsReview),
                LocalizableString(kind: .replacement(.init(argNumber: 1, formatSpecifier: "lld", variation: .plural(.other))), sourceKey: "%arg cats", targetLanguage: .french, translatedValue: "%arg chats", state: .translated)
            ]
        )
        
        let entry = try _CatalogEntry(from: stringGroup)
        
        #expect(entry.localizations?[.english]?.stringSet?.values == ["One", "", "Three"])
        #expect(entry.localizations?[.english]?.stringSet?.state == .needsReview)
        #expect(entry.localizations?[.french]?.substitutions?["arg1"]?.formatSpecifier == "lld")
        #expect(entry.localizations?[.french]?.substitutions?["arg1"]?.variations?.plural?[.other]?.stringUnit.value == "%arg chats")
    }
    
    @Test("init(from:) omits untranslated strings and produces nil localizations when empty")
    func initFromStringGroupOmitsUntranslatedStrings() throws {
        let stringGroup = LocalizableStringGroup(
            comment: nil,
            isCommentAutoGenerated: nil,
            extractionState: .manual,
            generatesSymbol: nil,
            shouldTranslate: nil,
            strings: [
                LocalizableString(kind: .standalone, sourceKey: "Hello", targetLanguage: .english, translatedValue: nil, state: .new)
            ]
        )
        
        let entry = try _CatalogEntry(from: stringGroup)
        
        #expect(entry.localizations == nil)
    }
}
